//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Domain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Domain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Domain", typeof(Domain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string AreYouSureDelete {
            get {
                return ResourceManager.GetString("AreYouSureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string ArticleBody {
            get {
                return ResourceManager.GetString("ArticleBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headline.
        /// </summary>
        public static string ArticleHeadline {
            get {
                return ResourceManager.GetString("ArticleHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account nr.
        /// </summary>
        public static string BankNr {
            get {
                return ResourceManager.GetString("BankNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaigns.
        /// </summary>
        public static string Campaigns {
            get {
                return ResourceManager.GetString("Campaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Chats.
        /// </summary>
        public static string Chats {
            get {
                return ResourceManager.GetString("Chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretension Chats.
        /// </summary>
        public static string ChatsInPretensions {
            get {
                return ResourceManager.GetString("ChatsInPretensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact type name too long..
        /// </summary>
        public static string ContactTypeNameLengthError {
            get {
                return ResourceManager.GetString("ContactTypeNameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact too long..
        /// </summary>
        public static string ContactValueLengthError {
            get {
                return ResourceManager.GetString("ContactValueLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        public static string Contracts {
            get {
                return ResourceManager.GetString("Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datetime.
        /// </summary>
        public static string Datetime {
            get {
                return ResourceManager.GetString("Datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal done:.
        /// </summary>
        public static string DealDone {
            get {
                return ResourceManager.GetString("DealDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals.
        /// </summary>
        public static string Deals {
            get {
                return ResourceManager.GetString("Deals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals in campaigns.
        /// </summary>
        public static string DealsInCampaign {
            get {
                return ResourceManager.GetString("DealsInCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign&apos;s description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products descriptions.
        /// </summary>
        public static string Descriptions {
            get {
                return ResourceManager.GetString("Descriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must not be empty!.
        /// </summary>
        public static string EmptyFieldError {
            get {
                return ResourceManager.GetString("EmptyFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string EntityPrimaryKey {
            get {
                return ResourceManager.GetString("EntityPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, Lastname.
        /// </summary>
        public static string FirstLastname {
            get {
                return ResourceManager.GetString("FirstLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name too long..
        /// </summary>
        public static string FirstnameLengthError {
            get {
                return ResourceManager.GetString("FirstnameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invited.
        /// </summary>
        public static string Invited {
            get {
                return ResourceManager.GetString("Invited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last, Firstname.
        /// </summary>
        public static string LastFirstname {
            get {
                return ResourceManager.GetString("LastFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name too long..
        /// </summary>
        public static string LastnameLengthError {
            get {
                return ResourceManager.GetString("LastnameLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input text too long.
        /// </summary>
        public static string LengthError {
            get {
                return ResourceManager.GetString("LengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input too short! Input must be atleast 3 letters!.
        /// </summary>
        public static string MinLengthError {
            get {
                return ResourceManager.GetString("MinLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My products.
        /// </summary>
        public static string MyProducts {
            get {
                return ResourceManager.GetString("MyProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is not selected!.
        /// </summary>
        public static string NotSelected {
            get {
                return ResourceManager.GetString("NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount percentage.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string Persons {
            get {
                return ResourceManager.GetString("Persons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People in chat.
        /// </summary>
        public static string PersonsInChat {
            get {
                return ResourceManager.GetString("PersonsInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People in contract.
        /// </summary>
        public static string PersonsInContract {
            get {
                return ResourceManager.GetString("PersonsInContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People in deal.
        /// </summary>
        public static string PersonsInDeal {
            get {
                return ResourceManager.GetString("PersonsInDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People in pretension.
        /// </summary>
        public static string PersonsInPretension {
            get {
                return ResourceManager.GetString("PersonsInPretension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture description.
        /// </summary>
        public static string PictureDescription {
            get {
                return ResourceManager.GetString("PictureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product pictures.
        /// </summary>
        public static string Pictures {
            get {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product pretensions.
        /// </summary>
        public static string Pretensions {
            get {
                return ResourceManager.GetString("Pretensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller.
        /// </summary>
        public static string ProductOwner {
            get {
                return ResourceManager.GetString("ProductOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raiting.
        /// </summary>
        public static string Raiting {
            get {
                return ResourceManager.GetString("Raiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered date.
        /// </summary>
        public static string Registered {
            get {
                return ResourceManager.GetString("Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone nr.
        /// </summary>
        public static string TelNr {
            get {
                return ResourceManager.GetString("TelNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insterted text was too long! Text must be less than 3500 letters!.
        /// </summary>
        public static string TooLongError {
            get {
                return ResourceManager.GetString("TooLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product trackin code.
        /// </summary>
        public static string TrackingCode {
            get {
                return ResourceManager.GetString("TrackingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Until.
        /// </summary>
        public static string Until {
            get {
                return ResourceManager.GetString("Until", resourceCulture);
            }
        }
    }
}
